apiVersion: v1
kind: Pod
metadata:
  name: inspect-me
  namespace: default
  labels:
    app: inspect-me
    team: training
spec:
  containers:
    - name: nginx
      image: nginx:1.28-alpine
      ports:
        - containerPort: 80
