apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-demo
  namespace: student-app
spec:
  replicas: 2
  selector:
    matchLabels: {app: affinity-demo}
  template:
    metadata:
      labels: {app: affinity-demo}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels: {app: affinity-demo}
      containers:
        - name: web
          image: nginx:1.27
