apiVersion: v1
kind: Pod
metadata:
  name: toleration-demo
  namespace: student-app
spec:
  tolerations:
    - key: dedicated
      operator: Equal
      value: platform
      effect: NoSchedule
  containers:
    - name: app
      image: nginx:1.27
