apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  namespace: student-app
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: manual
  resources:
    requests:
      storage: 500Mi
