apiVersion: v1
kind: Pod
metadata:
  name: student-web
  namespace: student-app
  labels:
    app: student-web
    version: v1
spec:
  containers:
    - name: web
      image: nginx:1.27
      ports:
        - containerPort: 80
