apiVersion: batch/v1
kind: CronJob
metadata:
  name: student-report
  namespace: student-app
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: report
              image: busybox:1.36
              command: ["sh","-c","date; echo scheduled training job"]
