apiVersion: batch/v1
kind: Job
metadata:
  name: student-job
  namespace: student-app
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: job
          image: busybox:1.36
          command: ["sh","-c","echo Kubernetes Job completed"]
  backoffLimit: 2
