apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress-tls
  namespace: web
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - training.example.local
      secretName: web-tls
  rules:
    - host: training.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-svc
                port:
                  number: 80
