apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-web-secure
  namespace: student-app
spec:
  replicas: 2
  selector:
    matchLabels: {app: student-web-secure}
  template:
    metadata:
      labels: {app: student-web-secure}
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: web
          image: nginxinc/nginx-unprivileged:1.27
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests: {cpu: 50m, memory: 64Mi}
            limits: {cpu: 250m, memory: 128Mi}
