apiVersion: v1
kind: Namespace
metadata:
  name: architecture-lab
---
apiVersion: v1
kind: Pod
metadata:
  name: arch-demo-pod
  namespace: architecture-lab
  labels:
    app: arch-demo
spec:
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.10
